// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1586520344);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1586520446);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.editDialog.confirmationHintShowCount", 1);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 5762);
user_pref("browser.cache.disk.capacity", 501760);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1586520314);
user_pref("browser.laterrun.bookkeeping.sessionCount", 3);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 81);
user_pref("browser.newtabpage.activity-stream.impressionId", "{bbdaede8-ea5a-4941-8fb9-45c9ad80bac0}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "amazon");
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://amazon.com\",\"label\":\"@amazon\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.runOncePerModification.displayBookmarksToolbar", "false");
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1586520334820");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1586522111820");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1586520325669");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1586523925669");
user_pref("browser.search.region", "DE");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20191113205532");
user_pref("browser.shell.checkDefaultBrowser", true);
user_pref("browser.shell.mostRecentDateSetAsDefault", "1586520466");
user_pref("browser.slowStartup.averageTime", 5326);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20191113205532");
user_pref("browser.startup.homepage_override.mstone", "68.2.0");
user_pref("browser.startup.lastColdStartupCheck", 1586520466);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\",\"foxyproxy_eric_h_jung-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"foxyproxy_eric_h_jung-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.Kali.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "68.2.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20191113205532");
user_pref("extensions.lastAppVersion", "68.2.0");
user_pref("extensions.lastPlatformVersion", "68.2.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.foxyproxy@eric.h.jung", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"f78195b5-7c15-4f71-94b9-fa9f0c6575eb\",\"fxmonitor@mozilla.org\":\"10a5ac64-02ab-4af9-ac44-d2163a0d1d74\",\"screenshots@mozilla.org\":\"6a430820-ca07-4976-8e1b-5388fcb7f218\",\"webcompat-reporter@mozilla.org\":\"b26d8a94-744d-400f-9305-0ac26b48141c\",\"webcompat@mozilla.org\":\"d17b2f5e-3225-446e-8836-72e26166e71c\",\"default-theme@mozilla.org\":\"3c59464f-f2f2-4841-bdd3-9b810520cecd\",\"google@search.mozilla.org\":\"113fe614-a826-4404-b3a4-880e5d1aa517\",\"amazondotcom@search.mozilla.org\":\"d4d5f85e-95e7-4a4c-b4a0-e1e58d2d5ff9\",\"bing@search.mozilla.org\":\"9cac9b39-dbb0-420a-ae32-773335b21cf6\",\"ddg@search.mozilla.org\":\"32e5ff41-0a4c-4a7e-873e-388f9f3de56a\",\"ebay@search.mozilla.org\":\"fd3cfd16-b87e-4dc6-a18b-c344f30a0297\",\"twitter@search.mozilla.org\":\"8400edc3-7077-47b3-b4ca-dbe6aec532a2\",\"wikipedia@search.mozilla.org\":\"febb5318-4164-4871-8a56-6fd31a57cf0e\",\"foxyproxy@eric.h.jung\":\"2061ba8e-b03b-4c99-bdd9-924a8cd1fdc1\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp-manager.buildID", "20191113205532");
user_pref("media.gmp-manager.lastCheck", 1586520340);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("pref.general.disable_button.default_browser", false);
user_pref("privacy.cpd.offlineApps", true);
user_pref("privacy.cpd.siteSettings", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("privacy.sanitize.timeSpan", 0);
user_pref("security.sandbox.content.tempDirSuffix", "63307ab2-7594-4b6e-a3c0-86ee7f2f1ba9");
user_pref("security.sandbox.plugin.tempDirSuffix", "5afbbb88-7f01-4404-85ba-f7d2ab4c717a");
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1586520465);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20191113205532");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
